### ISSUE TITLE
Detected blocking call to load_verify_locations

### ISSUE THREAD

**Issue by coserotondo** [koproductions-code/ha-groheblue#6]
Hi, just tried your integration. It successfully connect and retrieve data but I've this log at startup:

`Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x771889505d50>,) inside the event loop by custom integration 'groheblue' at custom_components/groheblue/__init__.py, line 58: devices = await client.get_devices() (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please report it to the author of the 'groheblue' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 783, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_setup await self.__async_setup_with_context(hass, integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context result = await component.async_setup_entry(hass, self) File "/config/custom_components/groheblue/__init__.py", line 58, in async_setup_entry devices = await client.get_devices()`

HA 2024.12.2

**Comment by koproductions-code** [comment]
Thanks for pointing this out. This log output is also produced by several other integrations and shouldn't limit the functionality. In a future release I will change the functionality of the code to address this warning.

**Comment by coserotondo** [comment]
Good to know. I integrates Grohe Blue Home using Node-Red and was looking to have more "native" integration. When I poll the API, I issue a `get_current_measurement `command to have the latest data. Also I use the `time_since_last_withdrawal` measure to check if I need a flush (I prefer doing it with my logic as from the app the auto flush doesn't work very well). the `time_since_last_withdrawal` is alreindy in the data the integration get (I did a quick test modifying the sensor definition in sensor.py and coordinator.py. It would be nice to expose the service for issuing the commands.

```
msg.payload = {  
    command : {
        //co2_status_reset: false,
        //tap_type: 0,
        //cleaning_mode: false,
        //filter_status_reset: false,
        get_current_measurement: true
        //tap_amount: 0,
        //factory_reset: false,
        //revoke_flush_confirmation: false,
        //exec_auto_flush: false
    }
};
```

**Comment by koproductions-code** [comment]
I've just pushed a new release **0.2.1**, which implements the new measure and an action for executing custom commands. Also I added a 'timestamp' measure to indicate when the data was last updated. Feel free to give it a try!

**Comment by coserotondo** [comment]
Thank you for updating.

I think the goal is to have the latest measurement at each update, so the `get_current_measurement `should be always called before the 5 mins update.
Of course this can be done inside HA with the service provided, but in this case, the polling should be configurable and eventually put at 0 (is it possible?) and calling inside HA `get_current_measurement `becomes a configurable refresh polling. Also the delay of the refresh after `get_current_measurement `shoud be configurable (maybe 5 sec are not enough for all situations). 

In Node what I do (maybe it is not very elegant...) is to send the `get_current_measurement `every 5 minutes and I try to get the latest measurement with:

```
if (msg.payload !== undefined && msg.payload.command !== undefined){
    let data = msg.payload;
    data.type = node.devicetype;
    let startDate = new Date();
    let startTime = startDate.getTime()
    let response = await node.config.session.setApplianceCommand(
        node.applianceIds.locationId,
        node.applianceIds.roomId,
        node.applianceIds.applianceId,
        data);
    // Hint: response is not used right now.
    
    let i = 0;
    let eventTime = 0;
    // Try to wait to get the latest measurement from device
    if (msg.payload.command.get_current_measurement == true){
        do {
            await sleep(1000 + (i * 1000));
            i += 10;
            let responseDataLatest = await node.config.session.getApplianceDataLatest(
                node.applianceIds.locationId,
                node.applianceIds.roomId,
                node.applianceIds.applianceId);
            let dataLatest = JSON.parse(responseDataLatest.text);
            let measurementTimestamp = dataLatest.data_latest.measurement.timestamp;
            let eventDate = new Date(measurementTimestamp);
            eventTime = eventDate.getTime()
        } while (i < 9 && eventTime < startTime);
    }

}
```

Maybe just putting some delay (as you did) could be enough but I think it is worth to "embed" the get_current_measurement command before every update.

Then, some suggestions for improvement:

Sensors:
Add `filter_change_count`, `filter_type`

Sensors SCHEMA:
Adding `state_class`, `device_class `(to better visualization, statistics)

For %:
```
state_class: measurement
unit_of_measurement: %
```

For volumes:
```
state_class: total
unit_of_measurement: L
device_class: volume
```

For duration (s, min):
```
state_class: measurement
unit_of_measurement: s | min
device_class: duration
```

For dates:
`device_class: timestamp`

For ENUM (`filter_type`):
`device_class: ENUM`
S_SIZE(1), ACTIVE_CARBON(2), ULTRA_SAFE(3), MAGNESIUM_PLUS(4), M_SIZE(5)

**Comment by koproductions-code** [comment]
Thanks for the recommendations. I agree that `get_current_measurement` should be called every sensor update and that it is better to check if the actual measurement happened (timestamp changed) and then update the sensors. I will also make the delay of the refresh and the update interval configurable in the next update. 

I don't really get what you mean with putting the polling at 0. Would that mean that polling would be deactivated and only manual polling using the service is allowed? Or do you mean setting the polling rate to update more frequently?

I will also add the sensors you recommended and update the schema of the sensors for better visualization and statistics. Sorry for not having done that in the first place, this is my first integration. 
Should be done this weekend.

**Comment by coserotondo** [comment]
The idea of polling at 0 was only if the `get_current_measurement ` had to be periodically called from HA and not "embedded". In other words to leverage the `get_current_measurement ` to both have fresh data and to update the integration with the new values.

If you make `get_current_measurement ` "embedded" (best solution), there is no need to put polling at 0, just make it configurable as the delay.

Thank you for your work. Maybe in the future I'll fork and trye to collaborate (need to learn python a little bit more...).

**Comment by coserotondo** [comment]
In relation with `Detected blocking call to load_verify_locations with args [...]`, is it linked to [this](https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs)? So there is the need to `from homeassistant.helpers.httpx_client import get_async_client`? Just learning.

**Comment by koproductions-code** [comment]
Yes it is related to that. I looked into it yesterday, but I would completely have to change the functionality of the groheblue python package to accept an external httpx client. It was also pretty dumb from me to use httpx and aiohttp in the package, which makes this change even harder. I will change it in the future but it does not have priority because it doesn't impact the functionality.

**Comment by koproductions-code** [comment]
I just released *0.3.0*. I have added the new sensors and state_class/device_class parameters for better statistics and visualization support. I also updated the groheblue python package to support the homeassistant httpx_client, so the warning mentioned above should no longer appear.
When polling, the integration now first requests a new measurement, waits until the new data is available from the API and then updates the sensor values. 
The integration also now has an option to set a custom polling interval, although I suspect that the Grohe API has some type of rate limiting to prevent requesting a new measurement too often. In my testing, a polling interval of 5 minutes worked best, but you can try yourself. Thank you for the recommendations. If you have any other issues/suggestions, please contact me.

**Comment by coserotondo** [comment]
Just installed on my dev instance. First configuration OK, I've all the sensors. But when I try to configure the integration, I have:

`Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble`

```
2024-12-16 17:12:44.018 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 262, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 77, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 342, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/groheblue/options_flow.py", line 16, in async_step_init
    default=self.config_entry.options.get("polling_interval", 300),
            ^^^^^^^^^^^^^^^^^
AttributeError: 'GroheBlueOptionsFlowHandler' object has no attribute 'config_entry'
```

**Comment by koproductions-code** [comment]
That could be because of your HA version, although I am not sure. On November 12, homeassistant published this blog post, which explains that you shouldn't define the config_entry variable manually anymore and that it will stop working with 2025.12, which is why I decided to use this new method: https://developers.home-assistant.io/blog/2024/11/12/options-flow/.
I will change it back to the old method for a few months and then update to use the new method some time in the future.

**Comment by coserotondo** [comment]
I'm on 2024.12.3.

**Comment by koproductions-code** [comment]
Just saw that my dev instance runs on the dev-branch which is currently 2025.1.0.dev0. Probably the reason why I didn't have issues.

**Comment by coserotondo** [comment]
> Just saw that my dev instance runs on the dev-branch which is currently 2025.1.0.dev0. Probably the reason why I didn't have issues.

My prod is 2024.12.3, My dev is 24.11.1. Let me update Dev and see.

**Comment by coserotondo** [comment]
So, I updated Dev at 2024.12.3 and with 0.3.0, no log message, with 0.3.1, log message, as expected.
Maybe you could check min HA version and stay with the new method?

**Comment by koproductions-code** [comment]
I think it is probably better to wait a bit, because 2024.12 is fairly new and only about 44% of people are currently on 2024.12 (https://analytics.home-assistant.io/). I will publish a new release in January with minimum requirement of 2024.12, but I will keep it like this for now because it does not break anything, just creates a log message.
